# -*- coding: utf-8 -*-
"""Parameter-Efficient-Fine-tuning-Foundation-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rh-dMFU_TSa8K9WFQsSwaBXFNPd15p5k

# **SetUp**
"""

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi

!pip install torch torchvision torchaudio
!pip install opencv-python matplotlib pandas tqdm scikit-learn scikit-image
!pip install monai einops timm
!pip install git+https://github.com/ChaoningZhang/MobileSAM.git

import os

PROJECT_DIR = "/content/drive/MyDrive/NuInsSeg_LoRA_SAM"
DATA_DIR = os.path.join(PROJECT_DIR, "data")
RESULTS_DIR = os.path.join(PROJECT_DIR, "results")
MODELS_DIR = os.path.join(PROJECT_DIR, "models")

for path in [PROJECT_DIR, DATA_DIR, RESULTS_DIR, MODELS_DIR]:
    os.makedirs(path, exist_ok=True)

print("Project ready:", PROJECT_DIR)

"""# **DataSet**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!wget -O NuInsSeg.zip "https://zenodo.org/records/10518968/files/NuInsSeg.zip?download=1"
!unzip -q NuInsSeg.zip -d /content/NuInsSeg

!cp -r /content/NuInsSeg/* "{DATA_DIR}"

import os

for root, dirs, files in os.walk(DATA_DIR):
    print(root, len(files))
    if len(files) > 0:
        print(files[:5])

"""# **Create Subset**"""

import os
import cv2
import torch
import numpy as np
from torch.utils.data import Dataset

class NuInsSegDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.samples = []
        self.transform = transform

        # recorrer todos los órganos
        for organ in os.listdir(root_dir):
            organ_path = os.path.join(root_dir, organ)

            img_dir = os.path.join(organ_path, "tissue images")
            mask_dir = os.path.join(organ_path, "label masks")

            if not os.path.exists(img_dir):
                continue

            for file in os.listdir(img_dir):
                if file.endswith(".png"):
                    img_path = os.path.join(img_dir, file)

                    mask_name = file.replace(".png", ".tif")
                    mask_path = os.path.join(mask_dir, mask_name)

                    if os.path.exists(mask_path):
                        self.samples.append((img_path, mask_path))

        print(f"Total samples: {len(self.samples)}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, mask_path = self.samples[idx]

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)

        # NORMALIZAR
        image = image / 255.0

        # a tensor
        image = torch.tensor(image, dtype=torch.float32).permute(2,0,1)
        mask = torch.tensor(mask, dtype=torch.long)

        return image, mask

dataset = NuInsSegDataset(DATA_DIR)

print(len(dataset))

img, mask = dataset[0]

print(img.shape, mask.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.title("Image")
plt.imshow(img.permute(1,2,0))

plt.subplot(1,2,2)
plt.title("Mask")
plt.imshow(mask)

plt.show()

"""# **MobileSAM + LoRA.**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!git clone https://github.com/ChaoningZhang/MobileSAM.git
# %cd MobileSAM

!pip install -e .

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/MobileSAM

!wget -O mobile_sam.pt https://github.com/ChaoningZhang/MobileSAM/raw/master/weights/mobile_sam.pt

import torch
import sys

sys.path.append("/content/MobileSAM")

from mobile_sam import sam_model_registry, SamPredictor

device = "cuda" if torch.cuda.is_available() else "cpu"

sam = sam_model_registry["vit_t"](checkpoint="/content/MobileSAM/mobile_sam.pt")
sam.to(device)

print("MobileSAM loaded on:", device)

"""# **Freeze Model**"""

for param in sam.parameters():
    param.requires_grad = False

"""# **Modulo Lora**"""

import torch.nn as nn
import math

class LoRALinear(nn.Module):
    def __init__(self, original_layer, r=4, alpha=8, dropout=0.0):
        super().__init__()

        self.original_layer = original_layer
        self.r = r
        self.alpha = alpha
        self.scaling = alpha / r

        in_features = original_layer.in_features
        out_features = original_layer.out_features

        self.lora_A = nn.Linear(in_features, r, bias=False)
        self.lora_B = nn.Linear(r, out_features, bias=False)
        self.dropout = nn.Dropout(dropout)

        nn.init.kaiming_uniform_(self.lora_A.weight, a=math.sqrt(5))
        nn.init.zeros_(self.lora_B.weight)

        for param in self.original_layer.parameters():
            param.requires_grad = False

    def forward(self, x):
        return self.original_layer(x) + self.lora_B(self.lora_A(self.dropout(x))) * self.scaling

"""# **Insert LoRA in MobileSAM**"""

def apply_lora_to_sam_image_encoder(model, r=4, alpha=8):
    lora_layers = []

    for name, module in model.image_encoder.named_modules():
        if isinstance(module, nn.Linear) and "qkv" in name:
            parent_name = name.rsplit(".", 1)[0]
            child_name = name.rsplit(".", 1)[1]

            parent = model.image_encoder
            for attr in parent_name.split("."):
                parent = getattr(parent, attr)

            original_layer = getattr(parent, child_name)
            lora_layer = LoRALinear(original_layer, r=r, alpha=alpha)
            setattr(parent, child_name, lora_layer)

            lora_layers.append(name)

    print("LoRA applied to:")
    for layer in lora_layers:
        print(layer)

    return model

sam = apply_lora_to_sam_image_encoder(sam, r=4, alpha=8)
sam.to(device)

"""# **Parameter**"""

for name, param in sam.named_parameters():
    if param.requires_grad:
        print(name, param.shape)

for name, param in sam.named_parameters():
    if param.requires_grad:
        print(name, param.shape)

"""# **Mask Box**"""

import numpy as np
import torch

def get_bounding_boxes_from_instance_mask(mask, min_area=10):
    """
    mask: numpy array H x W
          0 = background
          1,2,3,... = individual nuclei
    returns:
          boxes: Tensor [N, 4] in format x1, y1, x2, y2
          instance_ids: list of nucleus ids
    """
    boxes = []
    instance_ids = []

    ids = np.unique(mask)
    ids = ids[ids != 0]

    for instance_id in ids:
        binary = mask == instance_id
        area = binary.sum()

        if area < min_area:
            continue

        ys, xs = np.where(binary)

        x1, x2 = xs.min(), xs.max()
        y1, y2 = ys.min(), ys.max()

        boxes.append([x1, y1, x2, y2])
        instance_ids.append(instance_id)

    if len(boxes) == 0:
        return torch.zeros((0, 4), dtype=torch.float32), []

    boxes = torch.tensor(boxes, dtype=torch.float32)

    return boxes, instance_ids

"""# **Test**"""

img, mask = dataset[0]

mask_np = mask.numpy()

boxes, instance_ids = get_bounding_boxes_from_instance_mask(mask_np)

print("Number of nuclei:", len(instance_ids))
print("Boxes shape:", boxes.shape)
print("First boxes:", boxes[:5])

import matplotlib.pyplot as plt
import matplotlib.patches as patches

def show_image_with_boxes(image_tensor, boxes, max_boxes=30):
    image = image_tensor.permute(1, 2, 0).numpy()

    fig, ax = plt.subplots(figsize=(8, 8))
    ax.imshow(image)

    for box in boxes[:max_boxes]:
        x1, y1, x2, y2 = box.numpy()

        rect = patches.Rectangle(
            (x1, y1),
            x2 - x1,
            y2 - y1,
            linewidth=1,
            edgecolor="red",
            facecolor="none"
        )

        ax.add_patch(rect)

    ax.set_title(f"Bounding boxes shown: {min(len(boxes), max_boxes)}")
    ax.axis("off")
    plt.show()

show_image_with_boxes(img, boxes)

"""# **Update dataset with box and labels**"""

class NuInsSegSAMDataset(Dataset):
    def __init__(self, root_dir, image_size=1024):
        self.samples = []
        self.image_size = image_size

        for organ in os.listdir(root_dir):
            organ_path = os.path.join(root_dir, organ)

            img_dir = os.path.join(organ_path, "tissue images")
            mask_dir = os.path.join(organ_path, "label masks")

            if not os.path.exists(img_dir) or not os.path.exists(mask_dir):
                continue

            for file in os.listdir(img_dir):
                if file.endswith(".png"):
                    img_path = os.path.join(img_dir, file)
                    mask_name = file.replace(".png", ".tif")
                    mask_path = os.path.join(mask_dir, mask_name)

                    if os.path.exists(mask_path):
                        self.samples.append((img_path, mask_path))

        print(f"Total samples: {len(self.samples)}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, mask_path = self.samples[idx]

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)

        original_h, original_w = image.shape[:2]

        image_resized = cv2.resize(
            image,
            (self.image_size, self.image_size),
            interpolation=cv2.INTER_LINEAR
        )

        mask_resized = cv2.resize(
            mask,
            (self.image_size, self.image_size),
            interpolation=cv2.INTER_NEAREST
        )

        boxes, instance_ids = get_bounding_boxes_from_instance_mask(mask_resized)

        image_tensor = torch.tensor(image_resized / 255.0, dtype=torch.float32).permute(2, 0, 1)
        mask_tensor = torch.tensor(mask_resized, dtype=torch.long)

        sample = {
            "image": image_tensor,
            "mask": mask_tensor,
            "boxes": boxes,
            "instance_ids": instance_ids,
            "image_path": img_path,
            "mask_path": mask_path,
            "original_size": (original_h, original_w)
        }

        return sample

sam_dataset = NuInsSegSAMDataset(DATA_DIR, image_size=1024)

sample = sam_dataset[0]

print(sample["image"].shape)
print(sample["mask"].shape)
print(sample["boxes"].shape)
print(len(sample["instance_ids"]))

show_image_with_boxes(sample["image"], sample["boxes"], max_boxes=40)

"""# **Train/Val Split**"""

def sam_collate_fn(batch):
    return batch

from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Subset

indices = list(range(len(sam_dataset)))

train_idx, val_idx = train_test_split(
    indices,
    test_size=0.2,
    random_state=42
)

train_dataset = Subset(sam_dataset, train_idx)
val_dataset = Subset(sam_dataset, val_idx)

train_loader = DataLoader(
    train_dataset,
    batch_size=1,
    shuffle=True,
    collate_fn=sam_collate_fn
)

val_loader = DataLoader(
    val_dataset,
    batch_size=1,
    shuffle=False,
    collate_fn=sam_collate_fn
)

print(len(train_dataset), len(val_dataset))

def get_instance_binary_masks(mask, instance_ids):
    masks = []

    for instance_id in instance_ids:
        binary = (mask == instance_id).float()
        masks.append(binary)

    if len(masks) == 0:
        return torch.zeros((0, mask.shape[0], mask.shape[1]))

    return torch.stack(masks, dim=0)

import torch.nn.functional as F

def dice_loss(pred, target, eps=1e-6):
    pred = torch.sigmoid(pred)

    pred = pred.view(pred.shape[0], -1)
    target = target.view(target.shape[0], -1)

    intersection = (pred * target).sum(dim=1)
    union = pred.sum(dim=1) + target.sum(dim=1)

    dice = (2 * intersection + eps) / (union + eps)

    return 1 - dice.mean()


def segmentation_loss(pred_logits, gt_masks):
    bce = F.binary_cross_entropy_with_logits(pred_logits, gt_masks)
    dloss = dice_loss(pred_logits, gt_masks)

    return bce + dloss

optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, sam.parameters()),
    lr=1e-4,
    weight_decay=1e-4
)

"""# **Training**"""

from tqdm import tqdm

def train_one_epoch(model, dataloader, optimizer, device, max_boxes_per_image=20):
    model.train()
    total_loss = 0

    for batch in tqdm(dataloader):
        sample = batch[0]

        image = sample["image"].unsqueeze(0).to(device)
        mask = sample["mask"].to(device)
        boxes = sample["boxes"].to(device)
        instance_ids = sample["instance_ids"]

        if boxes.shape[0] == 0:
            continue

        # limitar cajas para ahorrar memoria
        if boxes.shape[0] > max_boxes_per_image:
            selected = torch.randperm(boxes.shape[0])[:max_boxes_per_image]
            boxes = boxes[selected]
            instance_ids = [instance_ids[i] for i in selected.cpu().numpy()]

        gt_instance_masks = get_instance_binary_masks(mask, instance_ids).to(device)

        optimizer.zero_grad()

        # image encoder
        image_embedding = model.image_encoder(image)

        # prompt encoder
        sparse_embeddings, dense_embeddings = model.prompt_encoder(
            points=None,
            boxes=boxes,
            masks=None
        )

        # mask decoder
        low_res_masks, iou_predictions = model.mask_decoder(
            image_embeddings=image_embedding,
            image_pe=model.prompt_encoder.get_dense_pe(),
            sparse_prompt_embeddings=sparse_embeddings,
            dense_prompt_embeddings=dense_embeddings,
            multimask_output=False
        )

        pred_masks = F.interpolate(
            low_res_masks,
            size=gt_instance_masks.shape[-2:],
            mode="bilinear",
            align_corners=False
        )

        pred_masks = pred_masks.squeeze(1)

        loss = segmentation_loss(pred_masks, gt_instance_masks)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(dataloader)

EPOCHS = 1

for epoch in range(EPOCHS):
    train_loss = train_one_epoch(
        sam,
        train_loader,
        optimizer,
        device,
        max_boxes_per_image=20
    )

    print(f"Epoch {epoch+1}/{EPOCHS} - Train Loss: {train_loss:.4f}")

torch.save(
    sam.state_dict(),
    os.path.join(MODELS_DIR, "mobilesam_lora_test.pth")
)

"""# **Dice Metrics**"""

def dice_score(pred_logits, gt_masks, threshold=0.5, eps=1e-6):
    pred = torch.sigmoid(pred_logits)
    pred = (pred > threshold).float()

    pred = pred.view(pred.shape[0], -1)
    gt_masks = gt_masks.view(gt_masks.shape[0], -1)

    intersection = (pred * gt_masks).sum(dim=1)
    union = pred.sum(dim=1) + gt_masks.sum(dim=1)

    dice = (2 * intersection + eps) / (union + eps)

    return dice.mean().item()

"""# **Validation**"""

@torch.no_grad()
def validate_one_epoch(model, dataloader, device, max_boxes_per_image=20):
    model.eval()

    total_loss = 0
    total_dice = 0
    n_batches = 0

    for batch in tqdm(dataloader):
        sample = batch[0]

        image = sample["image"].unsqueeze(0).to(device)
        mask = sample["mask"].to(device)
        boxes = sample["boxes"].to(device)
        instance_ids = sample["instance_ids"]

        if boxes.shape[0] == 0:
            continue

        if boxes.shape[0] > max_boxes_per_image:
            selected = torch.randperm(boxes.shape[0])[:max_boxes_per_image]
            boxes = boxes[selected]
            instance_ids = [instance_ids[i] for i in selected.cpu().numpy()]

        gt_instance_masks = get_instance_binary_masks(mask, instance_ids).to(device)

        image_embedding = model.image_encoder(image)

        sparse_embeddings, dense_embeddings = model.prompt_encoder(
            points=None,
            boxes=boxes,
            masks=None
        )

        low_res_masks, iou_predictions = model.mask_decoder(
            image_embeddings=image_embedding,
            image_pe=model.prompt_encoder.get_dense_pe(),
            sparse_prompt_embeddings=sparse_embeddings,
            dense_prompt_embeddings=dense_embeddings,
            multimask_output=False
        )

        pred_masks = F.interpolate(
            low_res_masks,
            size=gt_instance_masks.shape[-2:],
            mode="bilinear",
            align_corners=False
        )

        pred_masks = pred_masks.squeeze(1)

        loss = segmentation_loss(pred_masks, gt_instance_masks)
        dice = dice_score(pred_masks, gt_instance_masks)

        total_loss += loss.item()
        total_dice += dice
        n_batches += 1

    return total_loss / n_batches, total_dice / n_batches

EPOCHS = 5

history = []

for epoch in range(EPOCHS):
    train_loss = train_one_epoch(
        sam,
        train_loader,
        optimizer,
        device,
        max_boxes_per_image=20
    )

    val_loss, val_dice = validate_one_epoch(
        sam,
        val_loader,
        device,
        max_boxes_per_image=20
    )

    history.append({
        "epoch": epoch + 1,
        "train_loss": train_loss,
        "val_loss": val_loss,
        "val_dice": val_dice
    })

    print(
        f"Epoch {epoch+1}/{EPOCHS} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
        f"Val Dice: {val_dice:.4f}"
    )

import pandas as pd

history_df = pd.DataFrame(history)
history_df.to_csv(os.path.join(RESULTS_DIR, "training_history_test.csv"), index=False)

history_df

plt.figure(figsize=(7,5))
plt.plot(history_df["epoch"], history_df["train_loss"], label="Train Loss")
plt.plot(history_df["epoch"], history_df["val_loss"], label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training and Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(7,5))
plt.plot(history_df["epoch"], history_df["val_dice"], label="Validation Dice")
plt.xlabel("Epoch")
plt.ylabel("Dice")
plt.title("Validation Dice")
plt.legend()
plt.grid(True)
plt.show()



"""# **Evaluation**"""

from scipy.optimize import linear_sum_assignment
from skimage.measure import label
import numpy as np
import torch
import pandas as pd
import os
import matplotlib.pyplot as plt

def binary_stack_to_instance_mask(binary_masks, threshold=0.5):
    """
    binary_masks: Tensor [N, H, W], logits or probabilities
    returns instance mask H x W
    """
    if isinstance(binary_masks, torch.Tensor):
        masks = torch.sigmoid(binary_masks).detach().cpu().numpy()
    else:
        masks = binary_masks

    instance_mask = np.zeros(masks.shape[1:], dtype=np.int32)

    for i, m in enumerate(masks):
        binary = m > threshold
        instance_mask[binary] = i + 1

    return instance_mask

def compute_iou_matrix(gt, pred):
    gt_ids = np.unique(gt)
    pred_ids = np.unique(pred)

    gt_ids = gt_ids[gt_ids != 0]
    pred_ids = pred_ids[pred_ids != 0]

    iou_matrix = np.zeros((len(gt_ids), len(pred_ids)), dtype=np.float32)

    for i, gid in enumerate(gt_ids):
        gt_mask = gt == gid

        for j, pid in enumerate(pred_ids):
            pred_mask = pred == pid

            intersection = np.logical_and(gt_mask, pred_mask).sum()
            union = np.logical_or(gt_mask, pred_mask).sum()

            if union > 0:
                iou_matrix[i, j] = intersection / union

    return iou_matrix, gt_ids, pred_ids

def compute_aji(gt, pred):
    iou_matrix, gt_ids, pred_ids = compute_iou_matrix(gt, pred)

    if len(gt_ids) == 0 and len(pred_ids) == 0:
        return 1.0

    if len(gt_ids) == 0 or len(pred_ids) == 0:
        return 0.0

    row_ind, col_ind = linear_sum_assignment(-iou_matrix)

    intersection_sum = 0
    union_sum = 0

    matched_gt = set()
    matched_pred = set()

    for r, c in zip(row_ind, col_ind):
        if iou_matrix[r, c] > 0:
            gid = gt_ids[r]
            pid = pred_ids[c]

            gt_mask = gt == gid
            pred_mask = pred == pid

            intersection_sum += np.logical_and(gt_mask, pred_mask).sum()
            union_sum += np.logical_or(gt_mask, pred_mask).sum()

            matched_gt.add(gid)
            matched_pred.add(pid)

    for gid in gt_ids:
        if gid not in matched_gt:
            union_sum += (gt == gid).sum()

    for pid in pred_ids:
        if pid not in matched_pred:
            union_sum += (pred == pid).sum()

    if union_sum == 0:
        return 0.0

    return intersection_sum / union_sum

def compute_pq(gt, pred, iou_threshold=0.5):
    iou_matrix, gt_ids, pred_ids = compute_iou_matrix(gt, pred)

    if len(gt_ids) == 0 and len(pred_ids) == 0:
        return 1.0

    if len(gt_ids) == 0 or len(pred_ids) == 0:
        return 0.0

    row_ind, col_ind = linear_sum_assignment(-iou_matrix)

    tp = 0
    sum_iou = 0
    matched_gt = set()
    matched_pred = set()

    for r, c in zip(row_ind, col_ind):
        if iou_matrix[r, c] >= iou_threshold:
            tp += 1
            sum_iou += iou_matrix[r, c]
            matched_gt.add(gt_ids[r])
            matched_pred.add(pred_ids[c])

    fp = len(pred_ids) - len(matched_pred)
    fn = len(gt_ids) - len(matched_gt)

    denominator = tp + 0.5 * fp + 0.5 * fn

    if denominator == 0:
        return 0.0

    return sum_iou / denominator

@torch.no_grad()
def evaluate_full_metrics(model, dataloader, device, max_boxes_per_image=50):
    model.eval()

    dice_scores = []
    aji_scores = []
    pq_scores = []

    for batch in tqdm(dataloader):
        sample = batch[0]

        image = sample["image"].unsqueeze(0).to(device)
        gt_mask = sample["mask"].cpu().numpy()

        boxes = sample["boxes"].to(device)
        instance_ids = sample["instance_ids"]

        if boxes.shape[0] == 0:
            continue

        if boxes.shape[0] > max_boxes_per_image:
            selected = torch.randperm(boxes.shape[0])[:max_boxes_per_image]
            boxes = boxes[selected]
            instance_ids = [instance_ids[i] for i in selected.cpu().numpy()]

        gt_instance_masks = get_instance_binary_masks(
            sample["mask"], instance_ids
        ).to(device)

        image_embedding = model.image_encoder(image)

        sparse_embeddings, dense_embeddings = model.prompt_encoder(
            points=None,
            boxes=boxes,
            masks=None
        )

        low_res_masks, _ = model.mask_decoder(
            image_embeddings=image_embedding,
            image_pe=model.prompt_encoder.get_dense_pe(),
            sparse_prompt_embeddings=sparse_embeddings,
            dense_prompt_embeddings=dense_embeddings,
            multimask_output=False
        )

        pred_masks = F.interpolate(
            low_res_masks,
            size=gt_instance_masks.shape[-2:],
            mode="bilinear",
            align_corners=False
        ).squeeze(1)

        dice = dice_score(pred_masks, gt_instance_masks)

        pred_instance_mask = binary_stack_to_instance_mask(pred_masks)
        gt_instance_mask = sample["mask"].cpu().numpy()

        aji = compute_aji(gt_instance_mask, pred_instance_mask)
        pq = compute_pq(gt_instance_mask, pred_instance_mask)

        dice_scores.append(dice)
        aji_scores.append(aji)
        pq_scores.append(pq)

    return {
        "Dice": np.mean(dice_scores),
        "AJI": np.mean(aji_scores),
        "PQ": np.mean(pq_scores),
        "Dice_std": np.std(dice_scores),
        "AJI_std": np.std(aji_scores),
        "PQ_std": np.std(pq_scores)
    }

@torch.no_grad()
def save_visual_examples(model, dataloader, device, save_dir, max_examples=5, max_boxes_per_image=50):
    os.makedirs(save_dir, exist_ok=True)
    model.eval()

    saved = 0

    for batch in dataloader:
        if saved >= max_examples:
            break

        sample = batch[0]

        image = sample["image"].unsqueeze(0).to(device)
        image_np = sample["image"].permute(1, 2, 0).cpu().numpy()

        gt_mask = sample["mask"].cpu().numpy()
        boxes = sample["boxes"].to(device)
        instance_ids = sample["instance_ids"]

        if boxes.shape[0] == 0:
            continue

        if boxes.shape[0] > max_boxes_per_image:
            selected = torch.randperm(boxes.shape[0])[:max_boxes_per_image]
            boxes = boxes[selected]
            instance_ids = [instance_ids[i] for i in selected.cpu().numpy()]

        gt_instance_masks = get_instance_binary_masks(
            sample["mask"], instance_ids
        ).to(device)

        image_embedding = model.image_encoder(image)

        sparse_embeddings, dense_embeddings = model.prompt_encoder(
            points=None,
            boxes=boxes,
            masks=None
        )

        low_res_masks, _ = model.mask_decoder(
            image_embeddings=image_embedding,
            image_pe=model.prompt_encoder.get_dense_pe(),
            sparse_prompt_embeddings=sparse_embeddings,
            dense_prompt_embeddings=dense_embeddings,
            multimask_output=False
        )

        pred_masks = F.interpolate(
            low_res_masks,
            size=gt_instance_masks.shape[-2:],
            mode="bilinear",
            align_corners=False
        ).squeeze(1)

        pred_instance_mask = binary_stack_to_instance_mask(pred_masks)

        plt.figure(figsize=(15, 5))

        plt.subplot(1, 3, 1)
        plt.title("Original Image")
        plt.imshow(image_np)
        plt.axis("off")

        plt.subplot(1, 3, 2)
        plt.title("Ground Truth")
        plt.imshow(gt_mask)
        plt.axis("off")

        plt.subplot(1, 3, 3)
        plt.title("Prediction")
        plt.imshow(pred_instance_mask)
        plt.axis("off")

        out_path = os.path.join(save_dir, f"visual_example_{saved+1}.png")
        plt.savefig(out_path, dpi=300, bbox_inches="tight")
        plt.show()
        plt.close()

        saved += 1

    print(f"Saved {saved} visual examples in:", save_dir)

def build_lora_mobilesam(checkpoint_path="/content/MobileSAM/mobile_sam.pt", r=4, alpha=8):
    model = sam_model_registry["vit_t"](checkpoint=checkpoint_path)
    model.to(device)

    for param in model.parameters():
        param.requires_grad = False

    model = apply_lora_to_sam_image_encoder(model, r=r, alpha=alpha)
    model.to(device)

    return model

"""# **5-Fold Cross Validation**"""

from sklearn.model_selection import KFold
from torch.utils.data import Subset, DataLoader

def run_5fold_cross_validation(
    dataset,
    epochs=5,
    batch_size=1,
    lr=1e-4,
    max_boxes_per_image=20,
    r=4,
    alpha=8
):
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)

    fold_results = []

    all_indices = np.arange(len(dataset))

    for fold, (train_idx, val_idx) in enumerate(kfold.split(all_indices)):
        print("=" * 60)
        print(f"FOLD {fold + 1}/5")
        print("=" * 60)

        train_subset = Subset(dataset, train_idx)
        val_subset = Subset(dataset, val_idx)

        train_loader = DataLoader(
            train_subset,
            batch_size=batch_size,
            shuffle=True,
            collate_fn=sam_collate_fn
        )

        val_loader = DataLoader(
            val_subset,
            batch_size=batch_size,
            shuffle=False,
            collate_fn=sam_collate_fn
        )

        model = build_lora_mobilesam(r=r, alpha=alpha)

        optimizer = torch.optim.AdamW(
            filter(lambda p: p.requires_grad, model.parameters()),
            lr=lr,
            weight_decay=1e-4
        )

        fold_history = []

        for epoch in range(epochs):
            train_loss = train_one_epoch(
                model,
                train_loader,
                optimizer,
                device,
                max_boxes_per_image=max_boxes_per_image
            )

            val_loss, val_dice = validate_one_epoch(
                model,
                val_loader,
                device,
                max_boxes_per_image=max_boxes_per_image
            )

            fold_history.append({
                "fold": fold + 1,
                "epoch": epoch + 1,
                "train_loss": train_loss,
                "val_loss": val_loss,
                "val_dice": val_dice
            })

            print(
                f"Fold {fold+1} | Epoch {epoch+1}/{epochs} | "
                f"Train Loss: {train_loss:.4f} | "
                f"Val Loss: {val_loss:.4f} | "
                f"Val Dice: {val_dice:.4f}"
            )

        metrics = evaluate_full_metrics(
            model,
            val_loader,
            device,
            max_boxes_per_image=max_boxes_per_image
        )

        trainable_params = sum(
            p.numel() for p in model.parameters() if p.requires_grad
        )

        metrics["Fold"] = fold + 1
        metrics["Trainable Params"] = trainable_params

        fold_results.append(metrics)

        fold_history_df = pd.DataFrame(fold_history)
        fold_history_df.to_csv(
            os.path.join(RESULTS_DIR, f"fold_{fold+1}_history.csv"),
            index=False
        )

        torch.save(
            model.state_dict(),
            os.path.join(MODELS_DIR, f"mobilesam_lora_fold_{fold+1}.pth")
        )

        if fold == 0:
            save_visual_examples(
                model,
                val_loader,
                device,
                save_dir=os.path.join(RESULTS_DIR, "visual_examples"),
                max_examples=5,
                max_boxes_per_image=max_boxes_per_image
            )

        del model
        torch.cuda.empty_cache()

    results_df = pd.DataFrame(fold_results)

    cols = [
        "Fold",
        "Dice",
        "AJI",
        "PQ",
        "Dice_std",
        "AJI_std",
        "PQ_std",
        "Trainable Params"
    ]

    results_df = results_df[cols]

    results_df.to_csv(
        os.path.join(RESULTS_DIR, "5fold_results.csv"),
        index=False
    )

    summary = {
        "Method": "MobileSAM + LoRA",
        "Dice Mean": results_df["Dice"].mean(),
        "Dice Std": results_df["Dice"].std(),
        "AJI Mean": results_df["AJI"].mean(),
        "AJI Std": results_df["AJI"].std(),
        "PQ Mean": results_df["PQ"].mean(),
        "PQ Std": results_df["PQ"].std(),
        "Trainable Params": results_df["Trainable Params"].iloc[0]
    }

    summary_df = pd.DataFrame([summary])

    summary_df.to_csv(
        os.path.join(RESULTS_DIR, "final_summary.csv"),
        index=False
    )

    return results_df, summary_df

results_df, summary_df = run_5fold_cross_validation(
    sam_dataset,
    epochs=10,
    batch_size=1,
    lr=1e-4,
    max_boxes_per_image=50,
    r=4,
    alpha=8
)

results_df

summary_df

report_table = pd.DataFrame({
    "Method": ["MobileSAM + LoRA"],
    "Dice": [f"{summary_df['Dice Mean'][0]:.4f} ± {summary_df['Dice Std'][0]:.4f}"],
    "AJI": [f"{summary_df['AJI Mean'][0]:.4f} ± {summary_df['AJI Std'][0]:.4f}"],
    "PQ": [f"{summary_df['PQ Mean'][0]:.4f} ± {summary_df['PQ Std'][0]:.4f}"],
    "Trainable Parameters": [f"{int(summary_df['Trainable Params'][0]):,}"]
})

report_table

report_table.to_csv(
    os.path.join(RESULTS_DIR, "report_table.csv"),
    index=False
)

excel_path = os.path.join(RESULTS_DIR, "assignment3_results.xlsx")

with pd.ExcelWriter(excel_path) as writer:
    results_df.to_excel(writer, sheet_name="5Fold Results", index=False)
    summary_df.to_excel(writer, sheet_name="Summary", index=False)
    report_table.to_excel(writer, sheet_name="Report Table", index=False)

print("Saved:", excel_path)